# Comando para executar: docker compose up --build --force-recreate
version: '3.9'

networks:
  api-payments-network:
    driver: bridge

volumes:
  mongodbdata:

services:
  db_mongo:
    container_name: db_mongo
    image: 'mongo:6.0'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=apipayments
    ports:
      - "27017:27017"
    networks:
      - api-payments-network
    volumes:
      - mongodbdata:/var/lib/mongodb/data
#
#  api-payments:
#    container_name: api-payments
#    image: api-payments
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '8088:8088'
#      - '5006:5006'
#    environment:
#      PORT: 8088
#      DB_URL: db_postgres
#      DB_PORT: 5432
#      DB_USERNAME: postgres
#      DB_PASSWORD: postgres
#      DB_NAME: apipayments
#      NOTIFICATION_URL: https://pure-daily-grackle.ngrok-free.app/order/notifications
#      ADDITIONAL_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
#    networks:
#      - api-payments-network
#    depends_on:
#      - db_postgres

#  ngrok:
#    image: ngrok/ngrok:latest
#    container_name: ngrok
#    restart: unless-stopped
#    command:
#      - "start"
#      - "--all"
#      - "--config"
#      - "/etc/ngrok.yml"
#    volumes:
#      - ./ngrok.yml:/etc/ngrok.yml
#    ports:
#      - 4040:4040
#    networks:
#      - api-payments-network
#    depends_on:
#      - api-payments