server:
  port: ${PORT:8090}
  error:
    include-message: always

spring:
  application:
    name: api-payments-service
  data:
    mongodb:
      host: ${DB_CLUSTER_ENDPOINT:localhost}
      port: ${DB_PORT:27017}
      database: apipayments
      username: ${DB_USERNAME:mongo}
      password: ${DB_PASSWORD:mongo}
      authentication-database: admin
  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  output:
    ansi:
      enabled: Always

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

api:
  url:
    api-food: ${API_FOOD_URL:http://localhost:8088}
    api-order: ${API_ORDER_URL:http://localhost:8089}
#    api-payment: ${API_PAYMENT_URL:http://localhost:8090}

mercado-pago:
  url: "https://api.mercadopago.com"
  access-token: "Bearer APP_USR-151362775144770-012219-ad26be97b5a2ceab5965aaf6409a0d70-1650421194"
  notification-url: ${NOTIFICATION_URL:https://05c4-177-137-146-58.ngrok-free.app/order/notifications}