server:
  port: ${PORT:8090}
  error:
    include-message: always

spring:
  application:
    name: api-payments-service
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5434}/${DB_NAME:apipayments}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        show_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization:
  output:
    ansi:
      enabled: Always
  sql:
    init:
      mode: never

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

api:
  url:
    api-food: ${API_FOOD_URL:http://localhost:8088}
    api-order: ${API_ORDER_URL:http://localhost:8089}
#    api-payment: ${API_PAYMENT_URL:http://localhost:8090}

mercado-pago:
  url: "https://api.mercadopago.com"
  access-token: "Bearer APP_USR-151362775144770-012219-ad26be97b5a2ceab5965aaf6409a0d70-1650421194"
  notification-url: ${NOTIFICATION_URL:https://81b2-177-137-146-58.ngrok-free.app/order/notifications}